server.port=8081
spring.application.name=rag.chat.api
#spring.docker.compose.lifecycle-management=start_only
logging.level.root=INFO

spring.main.allow-bean-definition-overriding=true

spring.datasource.password=surve
spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/vectorStoreDB
spring.datasource.driver-class-name= org.postgresql.Driver
spring.jpa.hibernate.ddl-auto= none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

##Together AI Configs
together.ai.url= https://api.together.xyz
together.ai.url.completion= https://api.together.xyz/v1/chat/completions
together.ai.url.emeddings= https://api.together.xyz/v1/embeddings
together.ai.token= xxxx

spring.main.allow-circular-references= true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
openai.api.key=${OPENAI_API_KEY}
openai.api.url=https://api.openai.com/
openai.assistant_id="asst_K9ufIe4zr9rjxx1X9tWUp3i8"

